### ISSUE TITLE
この世の全ての夏コミ原稿がつつがなく終わりますように

### ISSUE THREAD

**Issue by fabon-f** [tsg-ut/tanzaku#10]
C100は8月13〜14日開催、あと約1ヶ月!

ウオー(発狂)

どうする どうする

**Comment by naan4UGen** [comment]
ウオー(発狂)(2)

**Comment by fabon-f** [comment]
夏コミ原稿、1つ目と2つ目が終わった。全部じゃないのがつらいとこですが……

**Comment by fabon-f** [comment]
夏コミ原稿3終わり! あと4つ目だけ……(これが一番ヤバい 大学のレポートとかもあるし)

**Comment by fabon-f** [comment]
夏コミは無事終わりました。原稿が無事だったかは人による。

**Comment by settyan117** [comment]
https://twitter.com/yashi09/status/1558019084813381632
