### ISSUE TITLE
おいしい麻婆豆腐が食べたい

### ISSUE THREAD

**Issue by moratorium08** [tsg-ut/tanzaku#26]
より具体的には http://www.kandayunrin.com/ にいってみたい。

この人の麻婆豆腐のレシピを参考にさせてもらっているので、「答え合わせ」がしたい

**Comment by hakatashi** [comment]
> お得なホリデーランチ: 2,035円

😯

**Comment by moratorium08** [comment]
FYI: 四川麻婆豆腐"激辛"ランチセットは1100円

**Comment by hakatashi** [comment]
> FIY

**Comment by moratorium08** [comment]
やりました。
