### ISSUE TITLE
ミスタードーナツの食べ放題に行き、ポンデリングを10個以上食べたい

### ISSUE THREAD

**Issue by naan4UGen** [tsg-ut/tanzaku#3]

**Comment by naan4UGen** [comment]
これ比較的真面目にやりたいので、メンツを募集して日程調整もしたいぜ(したいので)

**Comment by naan4UGen** [comment]
今週末、どうですか

**Comment by naan4UGen** [comment]
場所はミスタードーナツ中野ショップ( https://goo.gl/maps/uK1fP7dGzqqTTGo47 )を考えています

**Comment by hakatashi** [comment]
いく:heart:

**Comment by m1kit** [comment]
日曜なら、、、？

**Comment by naan4UGen** [comment]
日曜にしよ〜❤️

**Comment by naan4UGen** [comment]
だいたいの時間をきめたいのでだいたいの時間をきめ隊に入隊

**Comment by naan4UGen** [comment]
朝、昼、夕、どれがいいですか

**Comment by m1kit** [comment]
朝はいやだな

**Comment by naan4UGen** [comment]
わいわい

**Comment by naan4UGen** [comment]
明日の昼に予約を入れようかな(これは明日の昼に予約行動を行うということではなく、予約行動を行うことにより明日の昼の食べ放題を確定させるということ)

**Comment by naan4UGen** [comment]
今週行けなくなりました………(最悪)(会場からのブーイングの声)(社会性なし)

**Comment by naan4UGen** [comment]
食べ放題で10個のポンデリングと、1個のベイクチーズタルトドーナツ、1個のエビグラタンパイ、ドリンクを3杯注文しました！ありがとう七夕 フォーエバー七夕(七夕25日目)

**Comment by naan4UGen** [comment]
注文するだけして食べてないみたいな可能性が排除できない文になってたな 食べました
