### ISSUE TITLE
UD新ゴを手に入れたい

### ISSUE THREAD

**Issue by naan4UGen** [tsg-ut/tanzaku#5]

**Comment by naan4UGen** [comment]
ドラム式洗濯乾燥機より安い上に場所をあまり取らないのがよい 問題は最近あんまり文字を書いていないこと

**Comment by hakatashi** [comment]
フォントワークスのUD角ゴは代替になりませんか? 学生なら年990円で使えます。

https://lets.fontworks.co.jp/services/students

**Comment by naan4UGen** [comment]
ナンの中に眠る買い切り欲求に耐え切れなくなると思うので、厳しい

**Comment by naan4UGen** [comment]
これ叶った
